version: "3.2"

services:
  housing-search-api:
    image: housing-search-api
    build:
      context: .
      dockerfile: HousingSearchApi/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    environment:
      - ELASTICSEARCH_DOMAIN_URL=http://test-elasticsearch:9200
    networks:
      - elastic
    ports:
      - 3000:3000        
    depends_on:
      - test-elasticsearch

  housing-search-api-test:
    image: housing-search-api-test
    build:
      context: .
      dockerfile: HousingSearchApi.Tests/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    environment:
      - ELASTICSEARCH_DOMAIN_URL=http://test-elasticsearch:9200
    networks:
      - elastic
    depends_on:
      #- kibana
      - test-elasticsearch
      
  test-elasticsearch:
    image: test-elasticsearch
    container_name: test-elasticsearch
    build:
      context: .
      dockerfile: data/elasticsearch/Dockerfile
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata-test:/usr/share/elasticsearch/data
    networks:
      - elastic

  #kibana:
  #      image: docker.elastic.co/kibana/kibana:7.9.3
  #      ports:
  #          - "5601:5601"
  #      networks:
  #          - elastic
  #      depends_on:
  #          - test-elasticsearch

volumes:
    esdata-test:
        driver: local

networks:
  elastic:
    driver: bridge
