version: "3.2"

services:
  housing-search-api:
    image: housing-search-api
    build:
      context: HousingSearchApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000        
  housing-search-api-test:
    image: housing-search-api-test
    build:
      context: .
      dockerfile: HousingSearchApi.Tests/Dockerfile          
  test-elasticsearch:
    image: test-elasticsearch
    container_name: test-elasticsearch
    build:
      context: .
      dockerfile: data/elasticsearch/Dockerfile
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - esdata-test:/usr/share/elasticsearch/data
    networks:
      elastic:
        aliases:
          - test-elasticsearch
          - elastic
          - elasticsearch
  kibana:
        image: docker.elastic.co/kibana/kibana:7.9.3
        ports:
            - "5601:5601"
        networks:
            - elastic
        depends_on:
            - test-elasticsearch
volumes:
    esdata-test:
        driver: local
networks:
  elastic:
    driver: bridge
