services:
  housing-search-api:
    image: housing-search-api
    profiles:
      - api
    build:
      context: .
      dockerfile: HousingSearchApi/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    environment:
      SERVERHOST: http://localhost
      ELASTICSEARCH_DOMAIN_URL: http://test-elasticsearch:9200
    ports:
      - 3000:3000
    depends_on:
      - kibana
      - test-elasticsearch

  housing-search-api-test: &housing-search-api-test
    image: housing-search-api-test
    profiles:
      - test
    build:
      context: .
      dockerfile: HousingSearchApi.Tests/Dockerfile
      args:
      - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
      - SONAR_TOKEN=${SONAR_TOKEN}
      - ELASTICSEARCH_DOMAIN_URL=http://test-elasticsearch:9200
    environment:
      - ELASTICSEARCH_DOMAIN_URL=http://test-elasticsearch:9200
    depends_on:
      test-elasticsearch:
        condition: service_healthy
    command: ["dotnet", "test", "--filter", "HousingSearchApi.Tests.V1"]

  housing-search-api-test-v2:
    <<: *housing-search-api-test
    profiles:
      - test-v2
    command: ["dotnet", "test", "--filter", "HousingSearchApi.Tests.V2"]

  test-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: test-elasticsearch
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:9200/_cluster/health" ]
      interval: 10s
      timeout: 5s
      retries: 20
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      test-elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_HOSTS: http://test-elasticsearch:9200
      SERVER_HOST: 0.0.0.0
